/* The following code was generated by JFlex 1.4.3 on 11/29/09 8:01 PM */

package src;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/29/09 8:01 PM from the specification file
 * <tt>C:/Projects/BreezyCompiler/construction/Breezy.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\3\1\0\1\4\1\2\22\0\1\4\1\0\1\61"+
    "\2\0\1\34\2\0\1\52\1\53\1\6\1\32\1\56\1\33\1\57"+
    "\1\5\12\1\1\54\1\55\1\35\1\36\1\37\2\0\1\43\2\60"+
    "\1\46\1\40\6\60\1\44\1\60\1\45\1\47\1\60\1\41\1\50"+
    "\1\60\1\51\1\42\5\60\1\0\1\62\4\0\1\7\1\15\1\10"+
    "\1\24\1\11\1\25\1\16\1\23\1\17\2\60\1\22\1\30\1\20"+
    "\1\21\1\12\1\60\1\26\1\14\1\13\1\27\1\60\1\31\3\60"+
    "\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\1\2\3\1\4\1\5\1\6\12\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\4\7\1\16"+
    "\1\17\1\20\1\2\1\21\1\22\1\2\6\0\6\7"+
    "\1\23\7\7\1\24\1\25\3\7\1\26\2\27\1\1"+
    "\1\0\1\30\4\0\2\31\2\0\1\7\1\32\7\7"+
    "\1\33\4\7\1\34\1\35\1\30\4\0\1\36\1\37"+
    "\1\40\11\7\3\0\4\7\1\41\2\7\1\42\1\43"+
    "\1\0\1\44\1\0\1\45\2\7\1\46\1\7\1\47"+
    "\2\0\1\50\1\51\1\7\1\52\1\53\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\63\0\377\0\63"+
    "\0\u0132\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297"+
    "\0\u02ca\0\u02fd\0\63\0\146\0\63\0\u0330\0\63\0\u0363"+
    "\0\u0396\0\u03c9\0\u03fc\0\u042f\0\63\0\63\0\63\0\u0462"+
    "\0\63\0\u0495\0\u04c8\0\u0495\0\u04fb\0\u052e\0\u0561\0\u0594"+
    "\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9\0\u0132"+
    "\0\u072c\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e\0\63"+
    "\0\63\0\u0891\0\u08c4\0\u08f7\0\u0132\0\u092a\0\63\0\u0495"+
    "\0\u04c8\0\63\0\u095d\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\63"+
    "\0\u0a5c\0\u0a8f\0\u0ac2\0\u0132\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e"+
    "\0\u0bc1\0\u0bf4\0\u0c27\0\u0132\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3"+
    "\0\u0132\0\u0132\0\u04c8\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf\0\u0132"+
    "\0\u0132\0\u0132\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe\0\u0ef1"+
    "\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd\0\u0ff0\0\u1023\0\u1056\0\u1089"+
    "\0\u10bc\0\u10ef\0\u0132\0\u1122\0\u1155\0\u0132\0\u0132\0\u1188"+
    "\0\63\0\u11bb\0\u0132\0\u11ee\0\u1221\0\u0132\0\u1254\0\u0132"+
    "\0\u1287\0\u12ba\0\u0132\0\u0132\0\u12ed\0\63\0\63\0\u0132";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\2\11"+
    "\1\12\1\11\1\13\1\14\1\15\1\11\1\16\1\17"+
    "\4\11\1\20\1\21\2\11\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\2\11\1\32\1\11\1\33"+
    "\1\11\1\34\2\11\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\11\1\43\1\2\64\0\1\3\55\0\1\44"+
    "\6\0\1\5\3\0\1\45\5\0\1\46\10\0\1\47"+
    "\43\0\1\45\5\0\1\46\10\0\1\47\41\0\1\50"+
    "\1\51\55\0\1\11\5\0\23\11\6\0\12\11\6\0"+
    "\1\11\3\0\1\11\5\0\1\52\10\11\1\53\1\11"+
    "\1\54\7\11\6\0\12\11\6\0\1\11\3\0\1\11"+
    "\5\0\17\11\1\55\3\11\6\0\12\11\6\0\1\11"+
    "\3\0\1\11\5\0\4\11\1\56\16\11\6\0\12\11"+
    "\6\0\1\11\3\0\1\11\5\0\12\11\1\57\10\11"+
    "\6\0\12\11\6\0\1\11\3\0\1\11\5\0\16\11"+
    "\1\60\4\11\6\0\12\11\6\0\1\11\3\0\1\11"+
    "\5\0\12\11\1\61\5\11\1\62\2\11\6\0\12\11"+
    "\6\0\1\11\3\0\1\11\5\0\1\63\11\11\1\64"+
    "\5\11\1\65\2\11\6\0\12\11\6\0\1\11\3\0"+
    "\1\11\5\0\2\11\1\66\20\11\6\0\12\11\6\0"+
    "\1\11\3\0\1\11\5\0\14\11\1\67\6\11\6\0"+
    "\12\11\6\0\1\11\40\0\1\70\62\0\1\71\25\0"+
    "\1\11\5\0\23\11\6\0\1\11\1\72\10\11\6\0"+
    "\1\11\3\0\1\11\5\0\23\11\6\0\5\11\1\73"+
    "\4\11\6\0\1\11\3\0\1\11\5\0\23\11\6\0"+
    "\7\11\1\74\2\11\6\0\1\11\3\0\1\11\5\0"+
    "\23\11\6\0\10\11\1\75\1\11\6\0\1\11\4\0"+
    "\1\76\1\77\60\0\1\100\61\0\61\101\1\102\1\103"+
    "\10\0\1\104\63\0\1\105\62\0\1\106\51\0\2\50"+
    "\1\107\1\110\57\50\6\111\1\112\54\111\1\0\1\11"+
    "\5\0\1\11\1\113\21\11\6\0\12\11\6\0\1\11"+
    "\3\0\1\11\5\0\15\11\1\114\5\11\6\0\12\11"+
    "\6\0\1\11\3\0\1\11\5\0\5\11\1\115\15\11"+
    "\6\0\12\11\6\0\1\11\3\0\1\11\5\0\20\11"+
    "\1\116\2\11\6\0\12\11\6\0\1\11\3\0\1\11"+
    "\5\0\17\11\1\117\3\11\6\0\12\11\6\0\1\11"+
    "\3\0\1\11\5\0\12\11\1\120\10\11\6\0\12\11"+
    "\6\0\1\11\3\0\1\11\5\0\4\11\1\121\16\11"+
    "\6\0\12\11\6\0\1\11\3\0\1\11\5\0\21\11"+
    "\1\122\1\11\6\0\12\11\6\0\1\11\3\0\1\11"+
    "\5\0\13\11\1\123\7\11\6\0\12\11\6\0\1\11"+
    "\3\0\1\11\5\0\17\11\1\124\3\11\6\0\12\11"+
    "\6\0\1\11\3\0\1\11\5\0\11\11\1\125\11\11"+
    "\6\0\12\11\6\0\1\11\3\0\1\11\5\0\4\11"+
    "\1\126\16\11\6\0\12\11\6\0\1\11\3\0\1\11"+
    "\5\0\10\11\1\127\12\11\6\0\12\11\6\0\1\11"+
    "\3\0\1\11\5\0\23\11\6\0\2\11\1\130\7\11"+
    "\6\0\1\11\3\0\1\11\5\0\23\11\6\0\6\11"+
    "\1\131\3\11\6\0\1\11\3\0\1\11\5\0\23\11"+
    "\6\0\11\11\1\132\6\0\1\11\5\0\1\77\57\0"+
    "\61\101\1\133\1\103\10\0\1\134\70\0\1\135\57\0"+
    "\1\136\52\0\1\110\57\0\6\111\1\137\54\111\5\0"+
    "\1\110\1\112\55\0\1\11\5\0\14\11\1\140\6\11"+
    "\6\0\12\11\6\0\1\11\3\0\1\11\5\0\2\11"+
    "\1\141\20\11\6\0\12\11\6\0\1\11\3\0\1\11"+
    "\5\0\2\11\1\142\20\11\6\0\12\11\6\0\1\11"+
    "\3\0\1\11\5\0\10\11\1\143\12\11\6\0\12\11"+
    "\6\0\1\11\3\0\1\11\5\0\13\11\1\144\7\11"+
    "\6\0\12\11\6\0\1\11\3\0\1\11\5\0\14\11"+
    "\1\145\6\11\6\0\12\11\6\0\1\11\3\0\1\11"+
    "\5\0\6\11\1\146\14\11\6\0\12\11\6\0\1\11"+
    "\3\0\1\11\5\0\5\11\1\147\15\11\6\0\12\11"+
    "\6\0\1\11\3\0\1\11\5\0\1\11\1\150\21\11"+
    "\6\0\12\11\6\0\1\11\3\0\1\11\5\0\20\11"+
    "\1\151\2\11\6\0\12\11\6\0\1\11\3\0\1\11"+
    "\5\0\13\11\1\152\7\11\6\0\12\11\6\0\1\11"+
    "\3\0\1\11\5\0\23\11\6\0\3\11\1\153\6\11"+
    "\6\0\1\11\13\0\1\154\70\0\1\155\72\0\1\156"+
    "\33\0\5\111\1\110\1\137\54\111\1\0\1\11\5\0"+
    "\11\11\1\157\11\11\6\0\12\11\6\0\1\11\3\0"+
    "\1\11\5\0\2\11\1\160\20\11\6\0\12\11\6\0"+
    "\1\11\3\0\1\11\5\0\10\11\1\161\12\11\6\0"+
    "\12\11\6\0\1\11\3\0\1\11\5\0\2\11\1\162"+
    "\20\11\6\0\12\11\6\0\1\11\3\0\1\11\5\0"+
    "\2\11\1\163\20\11\6\0\12\11\6\0\1\11\3\0"+
    "\1\11\5\0\4\11\1\164\16\11\6\0\12\11\6\0"+
    "\1\11\3\0\1\11\5\0\17\11\1\165\3\11\6\0"+
    "\12\11\6\0\1\11\3\0\1\11\5\0\2\11\1\166"+
    "\20\11\6\0\12\11\6\0\1\11\3\0\1\11\5\0"+
    "\23\11\6\0\4\11\1\167\5\11\6\0\1\11\14\0"+
    "\1\170\70\0\1\171\70\0\1\172\35\0\1\11\5\0"+
    "\7\11\1\173\13\11\6\0\12\11\6\0\1\11\3\0"+
    "\1\11\5\0\1\174\22\11\6\0\12\11\6\0\1\11"+
    "\3\0\1\11\5\0\11\11\1\175\11\11\6\0\12\11"+
    "\6\0\1\11\3\0\1\11\5\0\17\11\1\176\3\11"+
    "\6\0\12\11\6\0\1\11\3\0\1\11\5\0\10\11"+
    "\1\177\12\11\6\0\12\11\6\0\1\11\3\0\1\11"+
    "\5\0\11\11\1\200\11\11\6\0\12\11\6\0\1\11"+
    "\15\0\1\201\67\0\1\202\43\0\1\11\5\0\11\11"+
    "\1\203\11\11\6\0\12\11\6\0\1\11\3\0\1\11"+
    "\5\0\7\11\1\204\13\11\6\0\12\11\6\0\1\11"+
    "\3\0\1\11\5\0\12\11\1\205\10\11\6\0\12\11"+
    "\6\0\1\11\16\0\1\206\62\0\1\207\47\0\1\11"+
    "\5\0\11\11\1\210\11\11\6\0\12\11\6\0\1\11"+
    "\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4896];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\3\1\1\11\1\1\1\11\12\1\1\11"+
    "\1\1\1\11\1\1\1\11\5\1\3\11\1\1\1\11"+
    "\2\1\6\0\16\1\2\11\5\1\1\11\1\1\1\0"+
    "\1\11\4\0\1\1\1\11\2\0\21\1\4\0\14\1"+
    "\3\0\11\1\1\0\1\11\1\0\6\1\2\0\3\1"+
    "\2\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
//Authored by Leighton, Jack, Jon, Ian, Elena, Clement 
//Adapted from pltsnow project by Jon, Cesar, Vinay, Sharadh

  public Parser yyparser;
  public int ln = 0;

  /* Default constructor */
  public Yylex(){}

  /* constructor taking an additional parser object */
  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }

  //Print to console
  private void p(String s){
	System.out.print(s + " ");
  }
  //Print line to console
  private void pl(String s){
	System.out.println(s);
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 142) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { pl("");
          }
        case 45: break;
        case 12: 
          { return yyparser.EQUALS;
          }
        case 46: break;
        case 28: 
          { return yyparser.LOG_OP_AND;
          }
        case 47: break;
        case 29: 
          { return yyparser.LOG_OP_NOT;
          }
        case 48: break;
        case 16: 
          { p("COLON");	return yyparser.COLON;
          }
        case 49: break;
        case 21: 
          { return yyparser.REL_OP_GE;
          }
        case 50: break;
        case 43: 
          { p("RETURNS");	return yyparser.RETURNS;
          }
        case 51: break;
        case 42: 
          { p("ACCEPTS");	return yyparser.ACCEPTS;
          }
        case 52: break;
        case 6: 
          { return yyparser.MUL;
          }
        case 53: break;
        case 15: 
          { p("RPAREN");	return yyparser.RPAREN;
          }
        case 54: break;
        case 13: 
          { return yyparser.REL_OP_GT;
          }
        case 55: break;
        case 38: 
          { p("NUMBER");	return yyparser.NUMBER;
          }
        case 56: break;
        case 34: 
          { p("WHILE");	return yyparser.WHILE;
          }
        case 57: break;
        case 19: 
          { p("IF");	return yyparser.IF;
          }
        case 58: break;
        case 32: 
          { p("TRUE");	return yyparser.TRUE;
          }
        case 59: break;
        case 36: 
          { pl("BEGIN");	return yyparser.BEGIN;
          }
        case 60: break;
        case 17: 
          { p("COMMA");	return yyparser.COMMA;
          }
        case 61: break;
        case 33: 
          { p("FALSE");	return yyparser.FALSE;
          }
        case 62: break;
        case 24: 
          { p(yytext());	yyparser.yylval = new ParserVal(yytext()); return yyparser.QUOTE;
          }
        case 63: break;
        case 10: 
          { return yyparser.MOD;
          }
        case 64: break;
        case 35: 
          { return yyparser.LOG_OP_EQUAL;
          }
        case 65: break;
        case 27: 
          { p("FOR");	return yyparser.FOR;
          }
        case 66: break;
        case 20: 
          { return yyparser.REL_OP_LE;
          }
        case 67: break;
        case 22: 
          { return yyparser.LOG_OP_OR;
          }
        case 68: break;
        case 18: 
          { p("DOT");	return yyparser.DOT;
          }
        case 69: break;
        case 5: 
          { return yyparser.DIV;
          }
        case 70: break;
        case 39: 
          { p("RETURN");	return yyparser.RETURN;
          }
        case 71: break;
        case 2: 
          { p("WHO KNOWS");	return 0;
          }
        case 72: break;
        case 37: 
          { p("STRING");	return yyparser.STRING;
          }
        case 73: break;
        case 11: 
          { return yyparser.REL_OP_LT;
          }
        case 74: break;
        case 30: 
          { p("EACH");	return yyparser.EACH;
          }
        case 75: break;
        case 26: 
          { pl("END");	return yyparser.END;
          }
        case 76: break;
        case 7: 
          { p(yytext());	yyparser.yylval = new ParserVal(yytext()); return yyparser.IDENTIFIER;
          }
        case 77: break;
        case 25: 
          { p("COMMENT");	return yyparser.COMMENT;
          }
        case 78: break;
        case 41: 
          { p("NOTHING");	return yyparser.NOTHING;
          }
        case 79: break;
        case 31: 
          { p("ELSE");	return yyparser.ELSE;
          }
        case 80: break;
        case 14: 
          { p("LPAREN");	return yyparser.LPAREN;
          }
        case 81: break;
        case 40: 
          { p("BOOLEAN");	return yyparser.BOOLEAN;
          }
        case 82: break;
        case 1: 
          { p("NUMERIC");	yyparser.yylval = new ParserVal(yytext()); return yyparser.NUMERIC;
          }
        case 83: break;
        case 23: 
          { pl("SEMICOLON");	return yyparser.SEMICOLON;
          }
        case 84: break;
        case 44: 
          { p("FUNCTION");	return yyparser.FUNCTION;
          }
        case 85: break;
        case 8: 
          { return yyparser.PLUS;
          }
        case 86: break;
        case 9: 
          { return yyparser.MINUS;
          }
        case 87: break;
        case 4: 
          { 
          }
        case 88: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
