/* The following code was generated by JFlex 1.4.3 on 12/17/09 9:30 PM */

package src;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/17/09 9:30 PM from the specification file
 * <tt>Breezy.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\3\1\0\1\4\1\2\22\0\1\4\1\0\1\63"+
    "\2\0\1\35\2\0\1\54\1\55\1\6\1\33\1\60\1\34\1\61"+
    "\1\5\12\1\1\56\1\57\1\36\1\37\1\40\2\0\1\44\2\62"+
    "\1\50\1\41\6\62\1\45\1\62\1\47\1\51\1\62\1\42\1\52"+
    "\1\46\1\53\1\43\5\62\1\0\1\64\4\0\1\7\1\15\1\10"+
    "\1\27\1\11\1\26\1\16\1\23\1\17\2\62\1\25\1\31\1\20"+
    "\1\24\1\12\1\62\1\21\1\14\1\13\1\30\1\62\1\32\1\62"+
    "\1\22\1\62\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\1\2\3\1\4\1\5\1\6\14\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\4\7\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\2\10\0\6\7"+
    "\1\24\10\7\1\25\1\26\3\7\1\27\1\1\1\0"+
    "\1\30\5\0\2\31\2\0\13\7\1\32\3\7\1\33"+
    "\1\34\1\30\1\0\1\35\4\0\1\7\1\36\1\37"+
    "\1\40\5\7\1\41\4\7\3\0\1\42\1\0\5\7"+
    "\1\43\1\7\1\44\1\7\1\0\1\45\2\0\1\46"+
    "\2\7\1\47\1\50\1\7\1\51\2\0\1\52\1\53"+
    "\1\54\1\7\1\55\1\56\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\65\0\u0109\0\65"+
    "\0\u013e\0\u0173\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1"+
    "\0\u02e6\0\u031b\0\u0350\0\u0385\0\65\0\152\0\65\0\u03ba"+
    "\0\65\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\65\0\65"+
    "\0\65\0\65\0\65\0\u04f8\0\u052d\0\u04f8\0\u0562\0\u0597"+
    "\0\u05cc\0\u0601\0\u0636\0\u066b\0\u06a0\0\u06d5\0\u070a\0\u073f"+
    "\0\u0774\0\u07a9\0\u07de\0\u0173\0\u0813\0\u0848\0\u087d\0\u08b2"+
    "\0\u08e7\0\u091c\0\u0951\0\u0986\0\65\0\65\0\u09bb\0\u09f0"+
    "\0\u0a25\0\u0173\0\u04f8\0\u052d\0\65\0\u0a5a\0\u0a8f\0\u0ac4"+
    "\0\u0af9\0\u0b2e\0\u0b63\0\65\0\u0b98\0\u0bcd\0\u0c02\0\u0c37"+
    "\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf"+
    "\0\u0e14\0\u0173\0\u0e49\0\u0e7e\0\u0eb3\0\u0173\0\u0173\0\u052d"+
    "\0\u0ee8\0\65\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u0173"+
    "\0\u1026\0\u0173\0\u105b\0\u1090\0\u10c5\0\u10fa\0\u112f\0\u0173"+
    "\0\u1164\0\u1199\0\u11ce\0\u1203\0\u1238\0\u126d\0\u12a2\0\u0173"+
    "\0\u12d7\0\u130c\0\u1341\0\u1376\0\u13ab\0\u13e0\0\u0173\0\u1415"+
    "\0\u0173\0\u144a\0\u147f\0\65\0\u14b4\0\u14e9\0\u0173\0\u151e"+
    "\0\u1553\0\u0173\0\u0173\0\u1588\0\u0173\0\u15bd\0\u15f2\0\65"+
    "\0\u0173\0\u0173\0\u1627\0\65\0\65\0\u0173";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\12\1\14\1\15\1\16\1\12\1\17"+
    "\1\20\1\21\1\12\1\22\2\12\1\23\3\12\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\2\12"+
    "\1\34\2\12\1\35\1\12\1\36\2\12\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\12\1\45\1\2\66\0"+
    "\1\3\57\0\1\46\6\0\1\5\1\47\2\0\1\50"+
    "\1\0\1\51\3\0\1\52\3\0\1\53\47\0\1\47"+
    "\2\0\1\50\1\0\1\51\3\0\1\52\3\0\1\53"+
    "\50\0\1\54\1\55\57\0\1\12\5\0\12\12\1\56"+
    "\11\12\6\0\13\12\6\0\1\12\3\0\1\12\5\0"+
    "\24\12\6\0\13\12\6\0\1\12\3\0\1\12\5\0"+
    "\1\57\15\12\1\60\5\12\6\0\13\12\6\0\1\12"+
    "\3\0\1\12\5\0\12\12\1\61\11\12\6\0\13\12"+
    "\6\0\1\12\3\0\1\12\5\0\4\12\1\62\17\12"+
    "\6\0\13\12\6\0\1\12\3\0\1\12\5\0\15\12"+
    "\1\63\6\12\6\0\13\12\6\0\1\12\3\0\1\12"+
    "\5\0\17\12\1\64\4\12\6\0\13\12\6\0\1\12"+
    "\3\0\1\12\5\0\15\12\1\65\3\12\1\66\2\12"+
    "\6\0\13\12\6\0\1\12\3\0\1\12\5\0\2\12"+
    "\1\67\21\12\6\0\13\12\6\0\1\12\3\0\1\12"+
    "\5\0\1\70\23\12\6\0\13\12\6\0\1\12\3\0"+
    "\1\12\5\0\1\71\14\12\1\72\3\12\1\73\2\12"+
    "\6\0\13\12\6\0\1\12\3\0\1\12\5\0\14\12"+
    "\1\74\7\12\6\0\13\12\6\0\1\12\41\0\1\75"+
    "\64\0\1\76\26\0\1\12\5\0\24\12\6\0\1\12"+
    "\1\77\11\12\6\0\1\12\3\0\1\12\5\0\24\12"+
    "\6\0\6\12\1\100\4\12\6\0\1\12\3\0\1\12"+
    "\5\0\24\12\6\0\10\12\1\101\2\12\6\0\1\12"+
    "\3\0\1\12\5\0\24\12\6\0\11\12\1\102\1\12"+
    "\6\0\1\12\3\0\1\103\63\0\63\104\1\105\1\106"+
    "\4\0\1\47\4\0\1\51\3\0\1\52\57\0\1\107"+
    "\74\0\1\110\55\0\1\111\64\0\1\112\53\0\2\54"+
    "\1\113\1\114\61\54\6\115\1\116\56\115\1\0\1\12"+
    "\5\0\12\12\1\117\11\12\6\0\13\12\6\0\1\12"+
    "\3\0\1\12\5\0\1\12\1\120\22\12\6\0\13\12"+
    "\6\0\1\12\3\0\1\12\5\0\5\12\1\121\16\12"+
    "\6\0\13\12\6\0\1\12\3\0\1\12\5\0\21\12"+
    "\1\122\2\12\6\0\13\12\6\0\1\12\3\0\1\12"+
    "\5\0\12\12\1\123\11\12\6\0\13\12\6\0\1\12"+
    "\3\0\1\12\5\0\15\12\1\124\6\12\6\0\13\12"+
    "\6\0\1\12\3\0\1\12\5\0\4\12\1\125\17\12"+
    "\6\0\13\12\6\0\1\12\3\0\1\12\5\0\22\12"+
    "\1\126\1\12\6\0\13\12\6\0\1\12\3\0\1\12"+
    "\5\0\4\12\1\127\17\12\6\0\13\12\6\0\1\12"+
    "\3\0\1\12\5\0\5\12\1\130\16\12\6\0\13\12"+
    "\6\0\1\12\3\0\1\12\5\0\16\12\1\131\5\12"+
    "\6\0\13\12\6\0\1\12\3\0\1\12\5\0\12\12"+
    "\1\132\11\12\6\0\13\12\6\0\1\12\3\0\1\12"+
    "\5\0\11\12\1\133\12\12\6\0\13\12\6\0\1\12"+
    "\3\0\1\12\5\0\10\12\1\134\13\12\6\0\13\12"+
    "\6\0\1\12\3\0\1\12\5\0\24\12\6\0\2\12"+
    "\1\135\10\12\6\0\1\12\3\0\1\12\5\0\24\12"+
    "\6\0\7\12\1\136\3\12\6\0\1\12\3\0\1\12"+
    "\5\0\24\12\6\0\12\12\1\137\6\0\1\12\2\0"+
    "\63\104\1\140\1\106\10\0\1\141\103\0\1\142\53\0"+
    "\1\143\61\0\1\144\54\0\1\114\61\0\6\115\1\145"+
    "\56\115\5\0\1\146\1\116\57\0\1\12\5\0\1\147"+
    "\23\12\6\0\13\12\6\0\1\12\3\0\1\12\5\0"+
    "\14\12\1\150\7\12\6\0\13\12\6\0\1\12\3\0"+
    "\1\12\5\0\2\12\1\151\21\12\6\0\13\12\6\0"+
    "\1\12\3\0\1\12\5\0\2\12\1\152\21\12\6\0"+
    "\13\12\6\0\1\12\3\0\1\12\5\0\10\12\1\153"+
    "\13\12\6\0\13\12\6\0\1\12\3\0\1\12\5\0"+
    "\16\12\1\154\5\12\6\0\13\12\6\0\1\12\3\0"+
    "\1\12\5\0\14\12\1\155\7\12\6\0\13\12\6\0"+
    "\1\12\3\0\1\12\5\0\6\12\1\156\15\12\6\0"+
    "\13\12\6\0\1\12\3\0\1\12\5\0\21\12\1\157"+
    "\2\12\6\0\13\12\6\0\1\12\3\0\1\12\5\0"+
    "\14\12\1\160\7\12\6\0\13\12\6\0\1\12\3\0"+
    "\1\12\5\0\5\12\1\161\16\12\6\0\13\12\6\0"+
    "\1\12\3\0\1\12\5\0\1\12\1\162\22\12\6\0"+
    "\13\12\6\0\1\12\3\0\1\12\5\0\16\12\1\163"+
    "\5\12\6\0\13\12\6\0\1\12\3\0\1\12\5\0"+
    "\24\12\6\0\3\12\1\164\7\12\6\0\1\12\13\0"+
    "\1\165\72\0\1\166\75\0\1\167\34\0\5\115\1\146"+
    "\1\145\56\115\2\0\1\113\1\114\62\0\1\12\5\0"+
    "\13\12\1\170\10\12\6\0\13\12\6\0\1\12\3\0"+
    "\1\12\2\0\1\171\2\0\24\12\6\0\13\12\6\0"+
    "\1\12\3\0\1\12\5\0\11\12\1\172\12\12\6\0"+
    "\13\12\6\0\1\12\3\0\1\12\5\0\2\12\1\173"+
    "\21\12\6\0\13\12\6\0\1\12\3\0\1\12\5\0"+
    "\10\12\1\174\13\12\6\0\13\12\6\0\1\12\3\0"+
    "\1\12\5\0\2\12\1\175\21\12\6\0\13\12\6\0"+
    "\1\12\3\0\1\12\5\0\12\12\1\176\11\12\6\0"+
    "\13\12\6\0\1\12\3\0\1\12\5\0\2\12\1\177"+
    "\21\12\6\0\13\12\6\0\1\12\3\0\1\12\5\0"+
    "\4\12\1\200\17\12\6\0\13\12\6\0\1\12\3\0"+
    "\1\12\5\0\2\12\1\201\21\12\6\0\13\12\6\0"+
    "\1\12\3\0\1\12\5\0\24\12\6\0\4\12\1\202"+
    "\6\12\6\0\1\12\14\0\1\203\72\0\1\204\65\0"+
    "\1\205\62\0\1\206\46\0\1\12\5\0\7\12\1\207"+
    "\14\12\6\0\13\12\6\0\1\12\3\0\1\12\5\0"+
    "\1\210\23\12\6\0\13\12\6\0\1\12\3\0\1\12"+
    "\5\0\11\12\1\211\12\12\6\0\13\12\6\0\1\12"+
    "\3\0\1\12\5\0\12\12\1\212\11\12\6\0\13\12"+
    "\6\0\1\12\3\0\1\12\5\0\11\12\1\213\12\12"+
    "\6\0\13\12\6\0\1\12\3\0\1\12\5\0\10\12"+
    "\1\214\13\12\6\0\13\12\6\0\1\12\3\0\1\12"+
    "\5\0\24\12\6\0\5\12\1\215\5\12\6\0\1\12"+
    "\15\0\1\216\71\0\1\217\72\0\1\220\37\0\1\12"+
    "\5\0\11\12\1\221\12\12\6\0\13\12\6\0\1\12"+
    "\3\0\1\12\5\0\7\12\1\222\14\12\6\0\13\12"+
    "\6\0\1\12\3\0\1\12\5\0\15\12\1\223\6\12"+
    "\6\0\13\12\6\0\1\12\16\0\1\224\64\0\1\225"+
    "\51\0\1\12\5\0\11\12\1\226\12\12\6\0\13\12"+
    "\6\0\1\12\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5724];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\3\1\1\11\1\1\1\11\14\1\1\11"+
    "\1\1\1\11\1\1\1\11\5\1\5\11\2\1\10\0"+
    "\17\1\2\11\5\1\1\0\1\11\5\0\1\1\1\11"+
    "\2\0\22\1\1\0\1\11\4\0\16\1\3\0\1\1"+
    "\1\0\11\1\1\0\1\11\2\0\7\1\2\0\1\11"+
    "\3\1\2\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
//Authored by Leighton, Jack, Jon, Ian, Elena, Clement 
//Adapted from pltsnow project by Jon, Cesar, Vinay, Sharadh

  public Parser yyparser;
  public int ln = 0;

  /* Default constructor */
  public Yylex(){}

  /* constructor taking an additional parser object */
  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }

  //Print to console
  private void p(String s){
            System.out.print(s + " ");
  }
  //Print line to console
  private void pl(String s){
            System.out.println(s);
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { p(yytext());	yyparser.yylval = new ParserVal(yytext()); return yyparser.NUMERIC;
          }
        case 48: break;
        case 34: 
          { p("ARRAY");    return yyparser.ARRAY;
          }
        case 49: break;
        case 33: 
          { p("HASH");    return yyparser.HASH;
          }
        case 50: break;
        case 3: 
          { pl("");
          }
        case 51: break;
        case 27: 
          { return yyparser.LOG_OP_AND;
          }
        case 52: break;
        case 28: 
          { return yyparser.LOG_OP_NOT;
          }
        case 53: break;
        case 16: 
          { p("COLON");	return yyparser.COLON;
          }
        case 54: break;
        case 22: 
          { return yyparser.REL_OP_GE;
          }
        case 55: break;
        case 46: 
          { p("RETURNS");	return yyparser.RETURNS;
          }
        case 56: break;
        case 45: 
          { p("ACCEPTS");	return yyparser.ACCEPTS;
          }
        case 57: break;
        case 6: 
          { return yyparser.MUL;
          }
        case 58: break;
        case 15: 
          { p("RPAREN");	return yyparser.RPAREN;
          }
        case 59: break;
        case 13: 
          { return yyparser.REL_OP_GT;
          }
        case 60: break;
        case 39: 
          { p("NUMBER");	return yyparser.NUMBER;
          }
        case 61: break;
        case 12: 
          { p("EQUALS");	return yyparser.EQUALS;
          }
        case 62: break;
        case 36: 
          { p("WHILE");	return yyparser.WHILE;
          }
        case 63: break;
        case 20: 
          { p("IF");	return yyparser.IF;
          }
        case 64: break;
        case 32: 
          { p("TRUE");	return yyparser.TRUE;
          }
        case 65: break;
        case 37: 
          { pl("BEGIN");	return yyparser.BEGIN;
          }
        case 66: break;
        case 18: 
          { p("COMMA");	return yyparser.COMMA;
          }
        case 67: break;
        case 35: 
          { p("FALSE");	return yyparser.FALSE;
          }
        case 68: break;
        case 24: 
          { p(yytext());	yyparser.yylval = new ParserVal(yytext()); return yyparser.QUOTE;
          }
        case 69: break;
        case 41: 
          { return yyparser.LOG_OP_EQUAL;
          }
        case 70: break;
        case 10: 
          { return yyparser.MOD;
          }
        case 71: break;
        case 26: 
          { p("FOR");	return yyparser.FOR;
          }
        case 72: break;
        case 21: 
          { return yyparser.REL_OP_LE;
          }
        case 73: break;
        case 23: 
          { return yyparser.LOG_OP_OR;
          }
        case 74: break;
        case 19: 
          { p("DOT");	return yyparser.DOT;
          }
        case 75: break;
        case 5: 
          { return yyparser.DIV;
          }
        case 76: break;
        case 40: 
          { p("RETURN");	return yyparser.RETURN;
          }
        case 77: break;
        case 2: 
          { p("WHO KNOWS");	return 0;
          }
        case 78: break;
        case 38: 
          { p("STRING");	return yyparser.STRING;
          }
        case 79: break;
        case 11: 
          { return yyparser.REL_OP_LT;
          }
        case 80: break;
        case 30: 
          { p("EACH");	return yyparser.EACH;
          }
        case 81: break;
        case 29: 
          { pl("END");	return yyparser.END;
          }
        case 82: break;
        case 7: 
          { p(yytext());	yyparser.yylval = new ParserVal(yytext()); return yyparser.IDENTIFIER;
          }
        case 83: break;
        case 25: 
          { p("COMMENT");	return yyparser.COMMENT;
          }
        case 84: break;
        case 44: 
          { p("NOTHING");	return yyparser.NOTHING;
          }
        case 85: break;
        case 42: 
          { p("ELSEIF");	return yyparser.ELSEIF;
          }
        case 86: break;
        case 31: 
          { p("ELSE");	return yyparser.ELSE;
          }
        case 87: break;
        case 14: 
          { p("LPAREN");	return yyparser.LPAREN;
          }
        case 88: break;
        case 43: 
          { p("BOOLEAN");	return yyparser.BOOLEAN;
          }
        case 89: break;
        case 17: 
          { pl("SEMICOLON");	return yyparser.SEMICOLON;
          }
        case 90: break;
        case 47: 
          { p("FUNCTION");	return yyparser.FUNCTION;
          }
        case 91: break;
        case 8: 
          { return yyparser.PLUS;
          }
        case 92: break;
        case 9: 
          { return yyparser.MINUS;
          }
        case 93: break;
        case 4: 
          { 
          }
        case 94: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
